-- V1__init_schema.sql

CREATE TABLE ledger_entries (
    entry_id bigint GENERATED BY DEFAULT AS IDENTITY,
    amount bigint,
    entry_type varchar(255) CHECK ((entry_type IN ('DEBIT','CREDIT'))),
    payment_id bigint,
    wallet_id bigint,
    PRIMARY KEY (entry_id)
);

CREATE TABLE payments (
    payment_id bigint GENERATED BY DEFAULT AS IDENTITY,
    amount bigint,
    created_at bigint NOT NULL,
    from_wallet_id bigint,
    idempotency_key varchar(255),
    max_retries integer NOT NULL,
    merchant_order_id varchar(255),
    payment_type varchar(255) CHECK ((payment_type IN ('P2P','MERCHANT'))),
    retry_count integer NOT NULL,
    status varchar(255) CHECK ((status IN ('CREATED','AUTHORIZED','CAPTURED','FAILED','RETRYING','EXPIRED','REFUNDED','REVERSED'))),
    to_wallet_id bigint,
    PRIMARY KEY (payment_id)
);

CREATE TABLE transactions (
    transaction_id bigint GENERATED BY DEFAULT AS IDENTITY,
    amount bigint,
    from_wallet_id bigint,
    payment_id bigint,
    to_wallet_id bigint,
    type varchar(255) CHECK ((type IN ('CREDIT','DEBIT','TRANSFER','DEPOSIT','WITHDRAW'))),
    PRIMARY KEY (transaction_id)
);

CREATE TABLE wallets (
    wallet_id bigint NOT NULL,
    balance bigint,
    phone_number bigint,
    status varchar(255) CHECK ((status IN ('ACTIVE','BLOCKED','CLOSED'))),
    user_id bigint,
    PRIMARY KEY (wallet_id)
);
